n1 = float(input('Digite a primeira nota: '))
n2 = float(input('Digite a segunda nota: '))
n3 = float(input('Digite a terceira nota: '))
media = (2*n1 + 3*n2 + 5*n3)/ (2+3+5)
print('A média do aluno(a) foi de {:.1f}'.format(media))