n1 = float(input('Digite o primeiro número: '))
n2 = float(input('Digite o segundo número: '))
n3 = float(input('Digite o terceiro número: '))
soma = (n1+n2+n3)
print('A soma entre {}, {} e {} é {}'.format(n1,n2,n3,soma))